# -*- coding: utf-8 -*-
"""Copy of 16d - 1 OOP Classes Working Together.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CiSdhgkRSSXdc8gMNGiFIgf3WPUuBp14
"""

class Pet:
    def __init__(self, name, age):
        self.name = name
        self.hunger = 80

    def __str__(self):
        return (
            f"Name: {self.name}\n"
            f"Age: {self.age}\n"
            f"Hunger: {self.hunger}\n"
        )

    def feed(self):
        self.hunger -= 20
        if self.hunger < 0:
            self.hunger = 0

class PetShelter:
    def __init__(self, name, manager):
        self.name = name
        self.pets = []
        self.manager = manager

    def find_pet(self, name):
        for pet in self.pets:
            if pet.name == name:
                return pet
        return None

    def add_pet(self, pet):
        """Add a new pet to the shelter"""
        if self.find_pet(pet.name) is None:
            self.pets.append(pet)
        else:
            print(f"A pet with this name {pet.name} already exists.")

    def get_all_pets(self):
        return self.pets

class Manager:
    def __init__(self, name, works_at_shelter):
        self.name = name
        self.shelter = works_at_shelter

    def feed_all_pets(self, pets):
        pets = self.shelter.get_all_pets()
        for pet in pets:
            pet.feed()

#Hi - I updated this file with some changes that some of you in the class commented on today.
#For example:

#1. I changed the method feed() to be called eat() since a Pet eats,

#2. I made the hunger attribute work the opposite way - if hunger is 0 then is full, if hunger is higher then is hungry. Up until 10.

#Have a look and tomorrow ask me any questions.

#There was some confusion as to how to use this - you need to first make objects of each of these types (Pet, PertShelter, and Manager) - and then use the methods of each class on the objects.

#Please ask me any questions!

#Thanks,
#Shlomit


class Pet:
    def __init__(self, name, age):
        self.name = name
        self.age = age
        self.hunger = 80

    def __str__(self):
        return (
            f"Name: {self.name}\n"
            f"Age: {self.age}\n"
            f"Hunger: {self.hunger}\n"
        )

    def eat(self):
        self.hunger -= 20
        if self.hunger < 0:
            self.hunger = 0
        print(f"{self.name} ate.")

    def time_passes(self):
        self.hunger += 20
        if self.hunger > 100:
            self.hunger = 100

class PetShelter:
    def __init__(self, name):
        self.name = name
        self.pets = []

    def __str__(self):
        pets_string = ""

        for pet in self.pets:
            pets_string += str(pet) + "\n"

        return (
            f"Shelter: {self.name}\n"
            f"Pets:\n"
            f"{pets_string}"
        )

    def find_pet(self, name):
        for pet in self.pets:
            if pet.name == name:
                return pet
        return None

    def add_pet(self, pet):
        """Add a new pet to the shelter"""
        self.pets.append(pet)

    def get_all_pets(self):
        return self.pets

    def get_number_pets(self):
        return len(self.pets)


class Manager:
    def __init__(self, name, shelterr):
        self.name = name
        self.shelter = shelter

    def feed_all_pets(self):
        pets = self.shelter.get_all_pets()
        if len(pets) == 0:
            print("There were no pets to feed.")
        else:
            for pet in pets:
                pet.eat()



cat1 = Pet("Cat", 10)
shelter = PetShelter("Shelter")
print(shelter.get_number_pets())
shelter.add_pet(cat1)
print(shelter.get_number_pets())
manager = Manager(cat1, shelter)

manager.feed_all_pets()

"""Continue with our 3 classes:


*   Pet
*   PetShelter
*   Manager

"""

class Pet:
    def __init__(self, name, age):
        self.name = name
        self.age = age
        self.hunger = 80

    def __str__(self):
        return (
            f"Name: {self.name}\n"
            f"Age: {self.age}\n"
            f"Hunger: {self.hunger}\n"
        )

    def eat(self):
        self.hunger -= 20
        if self.hunger < 0:
            self.hunger = 0
        print(f"{self.name} ate.")

class PetShelter:
    def __init__(self, name):
        self.name = name
        self.pets = []

    def __str__(self):
        pets_string = ""

        for pet in self.pets:
            pets_string += str(pet) + "\n"

        return (
            f"Shelter: {self.name}\n"
            f"Pets:\n"
            f"{pets_string}"
        )

    def find_pet(self, name):
        for pet in self.pets:
            if pet.name == name:
                return pet
        return None

    def add_pet(self, pet):
        """Add a new pet to the shelter"""
        self.pets.append(pet)

    def get_all_pets(self):
        return self.pets


class Manager:
    def __init__(self, name, shelter):
        self.name = name
        self.shelter = shelter

    def feed_all_pets(self):
        pets = self.shelter.get_all_pets()
        if len(pets) == 0:
            print("There were no pets to feed.")
        else:
            for pet in pets:
                pet.eat()

"""**1. Add a method to the PetShelter class to return the number of pets in the shelter**

You can call the method: `get_number_pets()`

**Test:**

* Add a few pets to the shelter.

* Call the new method and check that the number of pets is correct.`
"""

class Pet:
    def __init__(self, name, age):
        self.name = name
        self.age = age
        self.hunger = 80

    def __str__(self):
        return (
            f"Name: {self.name}\n"
            f"Age: {self.age}\n"
            f"Hunger: {self.hunger}\n"
        )

    def eat(self):
        self.hunger -= 20
        if self.hunger < 0:
            self.hunger = 0
        print(f"{self.name} ate.")


class PetShelter:
    def __init__(self, name):
        self.name = name
        self.pets = []

    def __str__(self):
        pets_string = ""

        for pet in self.pets:
            pets_string += str(pet) + "\n"

        return (
            f"Shelter: {self.name}\n"
            f"Pets:\n"
            f"{pets_string}"
        )

    def find_pet(self, name):
        for pet in self.pets:
            if pet.name == name:
                return pet
        return None

    def add_pet(self, pet):
        """Add a new pet to the shelter"""
        self.pets.append(pet)

    def get_all_pets(self):
        return self.pets


    def get_number_pets(self):
        return len(self.pets)


class Manager:
    def __init__(self, name, shelter):
        self.name = name
        self.shelter = shelter

    def feed_all_pets(self):
        pets = self.shelter.get_all_pets()
        if len(pets) == 0:
            print("There were no pets to feed.")
        else:
            for pet in pets:
                pet.eat()



shelter = PetShelter("Happy Tails")

pet1 = Pet("Milo", 2)
pet2 = Pet("Luna", 5)
pet3 = Pet("Charlie", 1)

shelter.add_pet(pet1)
shelter.add_pet(pet2)
shelter.add_pet(pet3)

print("Number of pets:", shelter.get_number_pets())

"""**2. Add a method to the Pet class to make the pet more hungry**

* You can call the method: `time_passes(hours_passed)`

  Since as time passes the animal will get more hungry
* This method increases the level of hunger according to the number of hours passed since the pet last ate.

  * If the number of hours_passed is between 1 - 3 then increase the hunger by 20

  * If the number of hours_passed is between 4 - 6 then increase the hunger by 50

  *  If the number of hours_passed is greater than 6 then increase the hunger by 80

  * The hunger value can only reach a max of 100

* Test this method


"""

class Pet:
    def __init__(self, name, age):
        self.name = name
        self.age = age
        self.hunger = 80

    def __str__(self):
        return (
            f"Name: {self.name}\n"
            f"Age: {self.age}\n"
            f"Hunger: {self.hunger}\n"
        )

    def eat(self):
        self.hunger -= 20
        if self.hunger < 0:
            self.hunger = 0
        print(f"{self.name} ate.")


    def time_passes(self, hours_passed):
        if 1 <= hours_passed <= 3:
            self.hunger += 20
        elif 4 <= hours_passed <= 6:
            self.hunger += 50
        elif hours_passed > 6:
            self.hunger += 80


        if self.hunger > 100:
            self.hunger = 100


class PetShelter:
    def __init__(self, name):
        self.name = name
        self.pets = []

    def __str__(self):
        pets_string = ""

        for pet in self.pets:
            pets_string += str(pet) + "\n"

        return (
            f"Shelter: {self.name}\n"
            f"Pets:\n"
            f"{pets_string}"
        )

    def find_pet(self, name):
        for pet in self.pets:
            if pet.name == name:
                return pet
        return None

    def add_pet(self, pet):
        self.pets.append(pet)

    def get_all_pets(self):
        return self.pets

    def get_number_pets(self):
        return len(self.pets)


class Manager:
    def __init__(self, name, shelter):
        self.name = name
        self.shelter = shelter

    def feed_all_pets(self):
        pets = self.shelter.get_all_pets()

        if len(pets) == 0:
            print("There were no pets to feed.")
        else:
            for pet in pets:
                pet.eat()




pet = Pet("Milo", 3)

print("Before time passes:")
print(pet)

pet.time_passes(2)

print("After 2 hours:")
print(pet)

pet.time_passes(5)

print("After another 5 hours:")
print(pet)

pet.time_passes(10)

print("After another 10 hours:")
print(pet)

"""**3. Vaccinate all pets in the shelter**

* Add a method called `vaccinate_all_pets()`

   * You decide into which class to add this method

* Add to the Pet class an attribute called `is_vaccinated = False`

* Add to the Pet class a method called `give_vaccination()`
   * This method should first check if the pet is_vaccinated, and only if False then to vaccinate it.
   * Vaccinating it means to change the value of `is_vaccinated` to `True`
   * And print a message that the animal was vaccinated.

**Test these new methods**
"""

class Pet:
    def __init__(self, name, age):
        self.name = name
        self.age = age
        self.hunger = 80
        self.is_vaccinated = False

    def __str__(self):
        return (
            f"Name: {self.name}\n"
            f"Age: {self.age}\n"
            f"Hunger: {self.hunger}\n"
            f"Vaccinated: {self.is_vaccinated}\n"
        )

    def eat(self):
        self.hunger -= 20
        if self.hunger < 0:
            self.hunger = 0
        print(f"{self.name} ate.")

    def time_passes(self, hours_passed):
        if 1 <= hours_passed <= 3:
            self.hunger += 20
        elif 4 <= hours_passed <= 6:
            self.hunger += 50
        elif hours_passed > 6:
            self.hunger += 80

        if self.hunger > 100:
            self.hunger = 100

    def give_vaccination(self):
        if not self.is_vaccinated:
            self.is_vaccinated = True
            print(f"{self.name} was vaccinated.")


class PetShelter:
    def __init__(self, name):
        self.name = name
        self.pets = []

    def __str__(self):
        pets_string = ""

        for pet in self.pets:
            pets_string += str(pet) + "\n"

        return (
            f"Shelter: {self.name}\n"
            f"Pets:\n"
            f"{pets_string}"
        )

    def find_pet(self, name):
        for pet in self.pets:
            if pet.name == name:
                return pet
        return None

    def add_pet(self, pet):
        self.pets.append(pet)

    def get_all_pets(self):
        return self.pets

    def get_number_pets(self):
        return len(self.pets)


class Manager:
    def __init__(self, name, shelter):
        self.name = name
        self.shelter = shelter

    def feed_all_pets(self):
        pets = self.shelter.get_all_pets()

        if len(pets) == 0:
            print("There were no pets to feed.")
        else:
            for pet in pets:
                pet.eat()

    def vaccinate_all_pets(self):
        pets = self.shelter.get_all_pets()

        if len(pets) == 0:
            print("There were no pets to vaccinate.")
        else:
            for pet in pets:
                pet.give_vaccination()




shelter = PetShelter("Happy Tails")

pet1 = Pet("Milo", 2)
pet2 = Pet("Luna", 4)
pet3 = Pet("Charlie", 1)

shelter.add_pet(pet1)
shelter.add_pet(pet2)
shelter.add_pet(pet3)

manager = Manager("Alice", shelter)

manager.vaccinate_all_pets()

print()
print(shelter)

"""**4. Adopt a  pet in the shelter**

* Add a method called `adopt_pet(Pet)`

   * You decide into which class to add this method
   * Inside this method the adopted pet should be removed from the list of pets in the shelter

**Test this new method**
"""

class Pet:
    def __init__(self, name, age):
        self.name = name
        self.age = age
        self.hunger = 80
        self.is_vaccinated = False

    def __str__(self):
        return (
            f"Name: {self.name}\n"
            f"Age: {self.age}\n"
            f"Hunger: {self.hunger}\n"
            f"Vaccinated: {self.is_vaccinated}\n"
        )

    def eat(self):
        self.hunger -= 20
        if self.hunger < 0:
            self.hunger = 0
        print(f"{self.name} ate.")

    def time_passes(self, hours_passed):
        if 1 <= hours_passed <= 3:
            self.hunger += 20
        elif 4 <= hours_passed <= 6:
            self.hunger += 50
        elif hours_passed > 6:
            self.hunger += 80

        if self.hunger > 100:
            self.hunger = 100

    def give_vaccination(self):
        if not self.is_vaccinated:
            self.is_vaccinated = True
            print(f"{self.name} was vaccinated.")


class PetShelter:
    def __init__(self, name):
        self.name = name
        self.pets = []

    def __str__(self):
        pets_string = ""

        for pet in self.pets:
            pets_string += str(pet) + "\n"

        return (
            f"Shelter: {self.name}\n"
            f"Pets:\n"
            f"{pets_string}"
        )

    def find_pet(self, name):
        for pet in self.pets:
            if pet.name == name:
                return pet
        return None

    def add_pet(self, pet):
        self.pets.append(pet)

    def adopt_pet(self, pet):
        if pet in self.pets:
            self.pets.remove(pet)
            print(f"{pet.name} was adopted.")
        else:
            print("Pet not found.")

    def get_all_pets(self):
        return self.pets

    def get_number_pets(self):
        return len(self.pets)


class Manager:
    def __init__(self, name, shelter):
        self.name = name
        self.shelter = shelter

    def feed_all_pets(self):
        pets = self.shelter.get_all_pets()

        if len(pets) == 0:
            print("There were no pets to feed.")
        else:
            for pet in pets:
                pet.eat()

    def vaccinate_all_pets(self):
        pets = self.shelter.get_all_pets()

        if len(pets) == 0:
            print("There were no pets to vaccinate.")
        else:
            for pet in pets:
                pet.give_vaccination()




shelter = PetShelter("Happy Tails")

pet1 = Pet("Milo", 2)
pet2 = Pet("Luna", 4)
pet3 = Pet("Charlie", 1)

shelter.add_pet(pet1)
shelter.add_pet(pet2)
shelter.add_pet(pet3)

print("Before adoption:")
print("Number of pets:", shelter.get_number_pets())
print(shelter)


shelter.adopt_pet(pet2)

print("\nAfter adoption:")
print("Number of pets:", shelter.get_number_pets())
print(shelter)

"""**5. Find the oldest pet in the shelter**

* Add a method called `find_oldest_pet()`

   * You decide into which class to add this method
   * This method loop through all of the pets in the shelter and find the oldest one and return the oldest Pet

**Test this new method**
Add a few pets with different ages to the shelter first, then you can test the new method.

"""

class Pet:
    def __init__(self, name, age):
        self.name = name
        self.age = age
        self.hunger = 80
        self.is_vaccinated = False

    def __str__(self):
        return (
            f"Name: {self.name}\n"
            f"Age: {self.age}\n"
            f"Hunger: {self.hunger}\n"
            f"Vaccinated: {self.is_vaccinated}\n"
        )

    def eat(self):
        self.hunger -= 20
        if self.hunger < 0:
            self.hunger = 0
        print(f"{self.name} ate.")

    def time_passes(self, hours_passed):
        if 1 <= hours_passed <= 3:
            self.hunger += 20
        elif 4 <= hours_passed <= 6:
            self.hunger += 50
        elif hours_passed > 6:
            self.hunger += 80

        if self.hunger > 100:
            self.hunger = 100

    def give_vaccination(self):
        if not self.is_vaccinated:
            self.is_vaccinated = True
            print(f"{self.name} was vaccinated.")


class PetShelter:
    def __init__(self, name):
        self.name = name
        self.pets = []

    def __str__(self):
        pets_string = ""

        for pet in self.pets:
            pets_string += str(pet) + "\n"

        return (
            f"Shelter: {self.name}\n"
            f"Pets:\n"
            f"{pets_string}"
        )

    def find_pet(self, name):
        for pet in self.pets:
            if pet.name == name:
                return pet
        return None

    def add_pet(self, pet):
        self.pets.append(pet)

    def adopt_pet(self, pet):
        if pet in self.pets:
            self.pets.remove(pet)
            print(f"{pet.name} was adopted.")
        else:
            print("Pet not found.")

    def get_all_pets(self):
        return self.pets

    def get_number_pets(self):
        return len(self.pets)


    def find_oldest_pet(self):
        if len(self.pets) == 0:
            return None

        oldest_pet = self.pets[0]

        for pet in self.pets:
            if pet.age > oldest_pet.age:
                oldest_pet = pet

        return oldest_pet


class Manager:
    def __init__(self, name, shelter):
        self.name = name
        self.shelter = shelter

    def feed_all_pets(self):
        pets = self.shelter.get_all_pets()

        if len(pets) == 0:
            print("There were no pets to feed.")
        else:
            for pet in pets:
                pet.eat()

    def vaccinate_all_pets(self):
        pets = self.shelter.get_all_pets()

        if len(pets) == 0:
            print("There were no pets to vaccinate.")
        else:
            for pet in pets:
                pet.give_vaccination()



shelter = PetShelter("Happy Tails")

pet1 = Pet("Milo", 2)
pet2 = Pet("Luna", 7)
pet3 = Pet("Charlie", 4)
pet4 = Pet("Max", 10)

shelter.add_pet(pet1)
shelter.add_pet(pet2)
shelter.add_pet(pet3)
shelter.add_pet(pet4)

oldest = shelter.find_oldest_pet()

print("The oldest pet is:")
print(oldest)

"""**6. Get pet names from a file, use random for pet ages**

* Create 2 lists: `pet_names` and `pet_ages`

* To fill names into `pet_names`:
  * Create a file that has the names of 10 pets
  * Read in the file and add all of the pets to a list called `pet_names`

* To fill ages into `pet_ages`:
  * Use random.randint(), where the ages are between 1 - 16.
  * Add 12 ages to the list

* Use a for loop and the zip() function to loop through the 2 lists and in the loop create the pets and add them to the shelter's list of pets.

**Test:**

* Check that the number of pets added to the shelter was 10.

* Write here why only 10 pets were added when there were 12 numbers in pet_ages.
"""



"""**7. Dictionary of Pets**

You can start with a dictionary such as this one:
```
pets_dict = {
    "Bella": 2,
    "Luna": 4,
    "Milo": 5,
    "Coco": 7
}
```

* Write a loop that creates a pet for each `key:value` in the dictionary.
   * Where the key is the pet name and the value is the pet age.
   * And adds the pets to an object of PetShelter.
   
"""



"""**8.  JSON file of pets**

* Using the dictionary of the last exercise, write the dictionary into a file called pets.json, using `json.dump()`. Use the parameter indent=4 so the file is easy to read.

* Then read the json file using `json.load()` into a new variable called `loaded_pets`.

* Add new pets to the pet shelter object, but only add the new pets where the age of the pet is greater than 4.

* Print each pet using the `get_all_pets()` method from the PetShelter object.
  * Check that there are only pets with the age greater than 4.
"""



"""**9. Fix this code:**


```
pet = Pet("Bella", 2)

Pet.eat()
```





"""



"""**10. Add a breed attribute to the Pet class**

* Add a new attribute to the Pet class called `breed`.

* In the __init__() method make this value have a default value to be None, this way it is optinal if they pass this value in or not when they create a pet.
  * Do this by writing: breed=None for the parameter value.

* Add to the __str__() method to print the value of breed, but only if it is not None.

**Test:**

*  Add a few pets to the shelter - some with a breed value and some withut a breed value.

*  Print all of the pets and check that the breed value is printed for the pets that have breeds, and is not printed for the pets that do not have breeds.


"""

class Pet:
    def __init__(self, name, age, breed=None):
        self.name = name
        self.age = age
        self.breed = breed
        self.hunger = 80
        self.is_vaccinated = False

    def __str__(self):
        breed_text = ""
        if self.breed is not None:
            breed_text = f"Breed: {self.breed}\n"

        return (
            f"Name: {self.name}\n"
            f"Age: {self.age}\n"
            f"{breed_text}"
            f"Hunger: {self.hunger}\n"
            f"Vaccinated: {self.is_vaccinated}\n"
        )

    def eat(self):
        self.hunger -= 20
        if self.hunger < 0:
            self.hunger = 0
        print(f"{self.name} ate.")

    def time_passes(self, hours_passed):
        if 1 <= hours_passed <= 3:
            self.hunger += 20
        elif 4 <= hours_passed <= 6:
            self.hunger += 50
        elif hours_passed > 6:
            self.hunger += 80

        if self.hunger > 100:
            self.hunger = 100

    def give_vaccination(self):
        if not self.is_vaccinated:
            self.is_vaccinated = True
            print(f"{self.name} was vaccinated.")


class PetShelter:
    def __init__(self, name):
        self.name = name
        self.pets = []

    def __str__(self):
        pets_string = ""

        for pet in self.pets:
            pets_string += str(pet) + "\n"

        return (
            f"Shelter: {self.name}\n"
            f"Pets:\n"
            f"{pets_string}"
        )

    def find_pet(self, name):
        for pet in self.pets:
            if pet.name == name:
                return pet
        return None

    def add_pet(self, pet):
        self.pets.append(pet)

    def adopt_pet(self, pet):
        if pet in self.pets:
            self.pets.remove(pet)
            print(f"{pet.name} was adopted.")
        else:
            print("Pet not found.")

    def get_all_pets(self):
        return self.pets

    def get_number_pets(self):
        return len(self.pets)

    def find_oldest_pet(self):
        if len(self.pets) == 0:
            return None

        oldest_pet = self.pets[0]

        for pet in self.pets:
            if pet.age > oldest_pet.age:
                oldest_pet = pet

        return oldest_pet


class Manager:
    def __init__(self, name, shelter):
        self.name = name
        self.shelter = shelter

    def feed_all_pets(self):
        pets = self.shelter.get_all_pets()

        if len(pets) == 0:
            print("There were no pets to feed.")
        else:
            for pet in pets:
                pet.eat()

    def vaccinate_all_pets(self):
        pets = self.shelter.get_all_pets()

        if len(pets) == 0:
            print("There were no pets to vaccinate.")
        else:
            for pet in pets:
                pet.give_vaccination()




shelter = PetShelter("Happy Tails")

pet1 = Pet("Milo", 2)
pet2 = Pet("Luna", 5, "Persian")
pet3 = Pet("Charlie", 1, "Golden Retriever")
pet4 = Pet("Max", 4)

shelter.add_pet(pet1)
shelter.add_pet(pet2)
shelter.add_pet(pet3)
shelter.add_pet(pet4)

print(shelter)

"""**10. Use the dogs API**

* Use the requests library to call the dogs api to get all breeds.

  * The docs: https://dog.ceo/dog-api/documentation/
  * The API: https://dog.ceo/api/breeds/list/all

  * The API returns a JSON that contains different breeds.

* Create 4 objects of Pets that are dogs, and for each one pass in a breed value that you get from the JSON result of the API call.


**Test:**
* Print all of the pets and check that they all have a different breed value that was from the JSON response.

"""

